### ISSUE TITLE
404 on data.json and /api/components/

### ISSUE THREAD

**Issue by Hoxolotl** [SimplyEdit/simplycode#12]
After cloning from the repo to http://timeboxplanner.site/simplycode/ the server cannot find data/components and data.json (404)

```
data.json is called in simply-edit.js 3440(xhr)
/api/components/ is called in  /simplycode/:167(fetch)
```

**Comment by ylebre** [comment]
Since simplyCode implements its own storage using the raw api / data api, we don't need to load data.json at all. It should be ok to add 'data-simply-storage="none"' to the the script source for simply-edit.js all the page frames.

**Comment by Hoxolotl** [comment]
the server wasn't configured, so currently no PUT would work, I know better now!

**Comment by Hoxolotl** [comment]
Not actually an issue.
