### ISSUE TITLE
polyfill.io supply chain attack

### ISSUE THREAD

**Issue by MarcHagen** [SimplyEdit/simplycode#37]
https://sansec.io/research/polyfill-supply-chain-attack

The original [polyfill author](https://x.com/triblondon/status/1761852117579427975) recommends to not use Polyfill at all, as it is no longer needed by modern browsers anyway.
> If your website uses [http://polyfill.io](https://t.co/3xHecLPXkB), remove it IMMEDIATELY.
> 
> I created the polyfill service project but I have never owned the domain name and I have had no influence over its sale.

https://github.com/SimplyEdit/simplycode/blob/eac155cd959972c53314ef6a1f28d952b6d2b276/www/simply-edit/index.php#L1540

**Comment by Potherca** [comment]
Thank you for reporting this! I've opened an MR to resolve this here (and in other affected projects).
